application: zawgyi-dev1
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: static/stylesheets
- url: /images
  static_dir: static/images
- url: /static
  static_dir: static

- url: /step1.*
  script: step1.py

- url: /step2.*
  script: step2.py

- url: /step3.*
  script: step3.py

- url: /step4.*
  script: step4.py
  
- url: /(newfeed.html|google72db3d6838b4c438.html)
  script: feedfetcher.py

- url: /.*
  script: main.py
